### PR TITLE
chore: divide around features

### PR DESCRIPTION
**Pull request by ydcjeff**
@vfdev-5

### CODE REVIEW

**Comment by vfdev-5** [comment]
Can we make them as here: 
Screen Shot 2021-08-09 at 11 42 36
?

**Comment by vfdev-5** [comment]
Thanks @ydcjeff for the updates. I'm not sure if it is much better... Let's keep as it is on master and update it with something else later

**Comment by trsvchn** [comment]
Looks not great as for me

**Comment by ydcjeff** [comment]
Superseded by #48

**Pull request closed without merging**
