### PR TITLE
refactor: new Ignite theme + dark mode

### LINKED ISSUE #22: Add search box
https://gohugo.io/tools/search/#readout

### LINKED ISSUE #54: Code cell font size issues
Using iOS safari, some code cells rendering problems appear. The font size seems not coherent.

Some screenshots below 

image

image

image

### LINKED ISSUE #62: Tag filtering for tutorials and how to guides

### LINKED ISSUE #64: Pagination pages
If we limit a page by a certain amount of tutorials or guides, we might need to have pagination pages for older content.
It doesn't make sense to have infinitely scrolling pages.

### LINKED ISSUE #65: Dark theme?

### PR DESCRIPTION
**Pull request by ydcjeff**
Highlights:

- Used [WindiCSS](https://windicss.org) for CSS.
- Custom theme in `theme` directory.
- Static HTML are injected at build time if possible.
- New shortcode `info`.

Links:
- https://next--pytorch-ignite.netlify.app/
- https://next--pytorch-ignite.netlify.app/getting-started/
- https://next--pytorch-ignite.netlify.app/tutorials/
- https://next--pytorch-ignite.netlify.app/how-to-guides/
- https://next--pytorch-ignite.netlify.app/blog/
- https://next--pytorch-ignite.netlify.app/tags/

fix #22
fix #54
fix #62
fix #64 
fix #65

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff thanks for the updates !
Here is how tweets are rendered:
Screen Shot 2021-09-15 at 13 34 02
Can we improve that as well ?

**Comment by ydcjeff** [comment]
@vfdev-5 Actually they are in the same size, url in first one is long so it breaks into another line.

**Comment by vfdev-5** [comment]
@ydcjeff I mean we could add boxes to them ...

**Comment by ydcjeff** [comment]
> @ydcjeff I mean we could add boxes to them ...

It already added

**Comment by sdesrozis** [comment]
@ydcjeff It looks great !!

**Comment by ydcjeff** [comment]
pinging @vfdev-5 @trsvchn @Priyansi for final review.
linkcheck job failure is expected since we haven't deployed to gh-pages.

**Comment by vfdev-5** [comment]
@ydcjeff few things to improve:

1) can we make tutorials first here and how-to guide after ?
Screen Shot 2021-09-25 at 15 47 25

2) why we still see on the left how-to guides and tutorials while seeing blog, ecosystem, about us etc pages ?
For blog we have to see list of posts...

Screen Shot 2021-09-25 at 15 49 28

**Review by vfdev-5 — APPROVED** [review]
Great job, Jeff !

**Comment by ydcjeff** [comment]
> 1. can we make tutorials first here and how-to guide after ?

Done in https://github.com/pytorch-ignite/pytorch-ignite.ai/pull/79/commits/da02c8d01ff0c04efa2c9fd61f8288ba43ec8d0d

> 2. why we still see on the left how-to guides and tutorials while seeing blog, ecosystem, about us etc pages ?

Tutorials and guides are shown as fallback. Blog list is now shown when viewing blog. https://github.com/pytorch-ignite/pytorch-ignite.ai/pull/79/commits/da02c8d01ff0c04efa2c9fd61f8288ba43ec8d0d

> 3. Can we hide "`" symbols in the text :

This is kinda new design for showing code texts and I suggest to give it a try for the community's feedback. So we don't need to override CSS.

**Comment by ydcjeff** [comment]
Docsearch PR is at https://github.com/algolia/docsearch-configs/pull/4654

**Comment by vfdev-5** [comment]
> Tutorials and guides are shown as default

It is a bit unusual to see that for other pages. Can we make an empty list by default ?

**Review by vfdev-5 — APPROVED** [review]
LGTM

**Comment by ydcjeff** [comment]
> It is a bit unusual to see that for other pages.

It is now forcing to show tutorials and how to guides lists by default since users will view the pages under there mostly.

**Pull request merged**
