### PR TITLE
feat: syntax highlight with shiki

### PR DESCRIPTION
**Pull request by ydcjeff**
This PR is trying to solve current syntax highlighting not aware of f-string. That's hugo syntax highligher limitation.
So I tried to find another working one and found [Shiki](https://github.com/shikijs/shiki) and it uses VSCode text mate grammar so we get an equal amount of syntax highlighting that is being used in VSCode extensively.

Since Shiki is used only for syntax highlighting, it doesn't make sense to ship Shiki on client side. So it's better to make highlighting up front. But that would bring npm package installation during development which we probably don't want to bring in, I think.

So Shiki is currently fetched from CDN and override syntax highlighting during development.
For the deployment, I added `package.json` for installation on Netlify (We can ignore that for development) and `highlight.mjs` parses the built `html` files and try to find the code blocks and rewrite the Shiki highlighted HTML in-place.

---

WDYT? Please comment your thoughts. For the highlighting theme, `github-dark` is currently used. You can find more on https://vscodethemes.com/

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff looks nice ! Can we use light-mode with this syntax highlighter ?

**Comment by ydcjeff** [comment]
> @ydcjeff looks nice ! Can we use light-mode with this syntax highlighter ?

Yes we can. We need to find a light theme that we want.

**Comment by vfdev-5** [comment]
> > @ydcjeff looks nice ! Can we use light-mode with this syntax highlighter ?
> 
> Yes we can. We need to find a light theme that we want.

github light : https://vscodethemes.com/e/GitHub.github-vscode-theme

**Review by vfdev-5 — APPROVED** [review]
LGTM, thanks @ydcjeff

**Comment by sdesrozis** [comment]
@ydcjeff I do appreciate ! It looks very nice !

**Review by vfdev-5 — APPROVED** [review]
LGTM

**Pull request merged**
