### PR TITLE
GAN Evaluation with FID and IS example

### PR DESCRIPTION
**Pull request by gucifer**
Google Colab Notebook example for GAN Evaluation using Frechet Inception Distance(FID) and Inception Score(IS).
Added Hugo based metadata using generate.py.

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff what should be done to render it as a markdown and display as a post ?

**Comment by ydcjeff** [comment]
@gucifer change the directory name to `static/posts` not `notebooks` and run

```sh
sh ./scripts/nb_to_md.sh ./static/posts ./content/posts
```

**Comment by vfdev-5** [comment]
@ydcjeff unfortunately, View on Github link does not work : https://github.com/pytorch-ignite/pytorch-ignite.ai/blob/gh-pages/posts/2021-08-11-GAN-evaluation-using-FID-and-IS.ipynb
Open in Colab neither...

**Comment by vfdev-5** [comment]
@gucifer please remove the last empty cell, otherwise it is rendered as 
image
and we do not understand this cell with "1" (which is the line number).

**Comment by trsvchn** [comment]
> @ydcjeff unfortunately, View on Github link does not work : https://github.com/pytorch-ignite/pytorch-ignite.ai/blob/gh-pages/posts/2021-08-11-GAN-evaluation-using-FID-and-IS.ipynb
> Open in Colab neither...

I think these links will work only after the deployment to GitHub Pages

@ydcjeff am i right?

**Comment by ydcjeff** [comment]
> > @ydcjeff unfortunately, View on Github link does not work : https://github.com/pytorch-ignite/pytorch-ignite.ai/blob/gh-pages/posts/2021-08-11-GAN-evaluation-using-FID-and-IS.ipynb
> > Open in Colab neither...
> 
> I think these links will work only after the deployment to GitHub Pages
> 
> @ydcjeff am i right?

Yes, it will only work after deploying to gh-pages.

**Comment by vfdev-5** [comment]
@gucifer you have to regenerate markdown as @ydcjeff suggested and did for you previously

**Comment by vfdev-5** [comment]
@gucifer let's replace the link behind "here" by https://pytorch.org/ignite/metrics.html#complete-list-of-metrics instead of https://pytorch.org/ignite/index.html

**Review by vfdev-5 — APPROVED** [review]
LGMT, thanks @gucifer , @ydcjeff

**Comment by vfdev-5** [comment]
@ydcjeff can we fix or bother about failing "submodule/check-update" ?

**Comment by ydcjeff** [comment]
> @ydcjeff can we fix or bother about failing "submodule/check-update" ?

That's because the examples repo has new notebooks and bot will create a new PR every 6 hours.
So we can safely merge this.

**Pull request merged**
