### PR TITLE
fix(search): bump @docsearch/js to 3.3 & add `appId` in config

### PR DESCRIPTION
**Pull request by ydcjeff**
[Algolia docsearch has moved to new version](https://github.com/algolia/docsearch-configs) and let admins directly edit the config via their web interface. So we need to update the docsearch version we are using to the latest stable one as well.

### CODE REVIEW

**Comment by vfdev-5** [comment]
@ydcjeff thanks for the PR !
Concerning failing linkcheck, I fixed the one with news_commentary. Do you think we can do anything with https://towardsdatascience.com ? Can we setup the checker to ignore them ?

**Comment by ydcjeff** [comment]
`check-ipynb-to-md` is expected to fail since it is blocked by https://github.com/pytorch-ignite/examples/pull/83

**Comment by ydcjeff** [comment]
@vfdev-5 the submodule failure is fixed in this PR and netlify failure is not updated in the check although the site is built successfully. https://deploy-preview-159--pytorch-ignite.netlify.app/

**Comment by vfdev-5** [comment]
@ydcjeff can we merge this PR ?

**Comment by ydcjeff** [comment]
@vfdev-5 yes, it's ready.

**Pull request merged**
